# Generated by Django 5.2.1 on 2025-05-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pokedex_no", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("weight", models.IntegerField()),
                ("is_default", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PokemonSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name_plural": "Pokemon species",
            },
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("hp", "Hp"),
                            ("attack", "Attack"),
                            ("defense", "Defense"),
                            ("special-attack", "Special Attack"),
                            ("special-defense", "Special Defense"),
                            ("speed", "Speed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_battle_only", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.CreateModel(
            name="PokemonForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("form_name", models.CharField(max_length=64)),
                ("is_default", models.BooleanField()),
                ("pokemon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pokemon")),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pokemonspecies"),
        ),
        migrations.CreateModel(
            name="PokemonStatValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.IntegerField()),
                ("pokemon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pokemon")),
                (
                    "stat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pokemonstat"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="types",
            field=models.ManyToManyField(to="api.pokemontype"),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
