# Generated by Django 5.2.1 on 2025-05-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pokedex_no", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("weight", models.IntegerField()),
                (
                    "species",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.pokemonspecies"),
                ),
                ("types", models.ManyToManyField(to="api.pokemontype")),
            ],
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
