# Generated by Django 5.2.1 on 2025-05-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_pokemon_pokemonspecies_pokemonstat_pokemontype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="is_default",
            new_name="is_species_default",
        ),
    ]
