# Generated by Django 5.2.1 on 2025-05-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0002_pokemon_pokemonability_pokemonspecies_pokemonstat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonEvolutionChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_evolution", models.JSONField()),
                ("second_evolution", models.JSONField(blank=True, null=True)),
                (
                    "unevolved",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemonspecies"
                    ),
                ),
            ],
        ),
    ]
