# Generated by Django 5.2.1 on 2025-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0002_pokemon_pokemonspecies_pokemonstat_pokemontype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="base_experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="height",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
