# Generated by Django 5.2.1 on 2025-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0002_pokemon_pokemonability_pokemonspecies_pokemonstat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonevolutionchain",
            name="first_evolution",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
