# Generated by Django 5.2.1 on 2025-06-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0002_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pokedex_no", models.IntegerField()),
                ("name", models.CharField(max_length=64)),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("base_experience", models.IntegerField()),
                ("is_default", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name_plural": "Pokemon abilities",
            },
        ),
        migrations.CreateModel(
            name="PokemonSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name_plural": "Pokemon species",
            },
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("hp", "Hp"),
                            ("attack", "Attack"),
                            ("defense", "Defense"),
                            ("special-attack", "Special Attack"),
                            ("special-defense", "Special Defense"),
                            ("speed", "Speed"),
                            ("accuracy", "Accuracy"),
                            ("evasion", "Evasion"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_battle_only", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="PokemonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.CreateModel(
            name="PokemonAbilityValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_hidden", models.BooleanField()),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemonability"
                    ),
                ),
                (
                    "pokemon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemon"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("form", models.CharField(max_length=64)),
                ("is_default", models.BooleanField()),
                (
                    "pokemon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemon"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonEvolutionChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("unevolved", models.CharField(max_length=64)),
                ("first_evolution", models.JSONField(blank=True, null=True)),
                ("second_evolution", models.JSONField(blank=True, null=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemonspecies"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="species",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemonspecies"),
        ),
        migrations.CreateModel(
            name="PokemonStatValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "pokemon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemon"),
                ),
                (
                    "stat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pokeapp.pokemonstat"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pokemon",
            name="types",
            field=models.ManyToManyField(to="pokeapp.pokemontype"),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
