# Generated by Django 5.2.1 on 2025-05-31 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0003_pokemon_base_experience_pokemon_height"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="is_species_default",
            new_name="is_default",
        ),
    ]
