# Generated by Django 5.2.1 on 2025-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0003_pokemon_pokemonability_pokemonspecies_pokemonstat_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pokemonabilityvalue",
            constraint=models.UniqueConstraint(
                fields=("pokemon", "ability", "is_hidden"), name="unique_ability_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="pokemonstatvalue",
            constraint=models.UniqueConstraint(fields=("pokemon", "stat"), name="unique_stat_value"),
        ),
    ]
