# Generated by Django 5.2.1 on 2025-05-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0004_rename_is_species_default_pokemon_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
    ]
