# Generated by Django 5.2.1 on 2025-06-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0004_pokemonabilityvalue_unique_ability_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(related_name="abilities", to="pokeapp.pokemonabilityvalue"),
        ),
    ]
