# Generated by Django 5.2.1 on 2025-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0005_pokemonability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemonability",
            options={"verbose_name_plural": "Pokemon abilities"},
        ),
        migrations.AddField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(to="pokeapp.pokemonability"),
        ),
    ]
