# Generated by Django 5.2.1 on 2025-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0006_alter_pokemon_abilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="abilities",
            field=models.ManyToManyField(related_name="pokemons", to="pokeapp.pokemonabilityvalue"),
        ),
    ]
