# Generated by Django 5.2.1 on 2025-05-31 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0006_alter_pokemonability_options_pokemon_abilities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemonform",
            old_name="form_name",
            new_name="form",
        ),
        migrations.RemoveField(
            model_name="pokemonform",
            name="name",
        ),
    ]
