# Generated by Django 5.2.1 on 2025-05-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokeapp", "0007_rename_form_name_pokemonform_form_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonstat",
            name="name",
            field=models.CharField(
                choices=[
                    ("hp", "Hp"),
                    ("attack", "Attack"),
                    ("defense", "Defense"),
                    ("special-attack", "Special Attack"),
                    ("special-defense", "Special Defense"),
                    ("speed", "Speed"),
                    ("accuracy", "Accuracy"),
                    ("evasion", "Evasion"),
                ],
                max_length=64,
            ),
        ),
    ]
